### ISSUE TITLE
FRGK - link colors, hover states and buttons

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/bene#123]
## Overview
Need to polish all of these.
## This ticket is done when:

**Utility nav**
- [x] hover state is hex#88287B
- [x] active state is hex#88287B

**Sub Nav**
- [ ] hover state is hex#88287B
- [ ] active state is hex#88287B

**Body Copy**
- [x] link color is hex#88287B
- [x] hover state is hex#55184D

**Headers**
- [x] link color is the same as the header style (no link color, no underline)
- [x] hover state is hex#727171

**Buttons in the WYSIWYG**
Buttons in the WYSIWYG are currently the wrong style. They should look like this:
![screen shot 2017-09-21 at 4 32 58 pm](https://user-images.githubusercontent.com/21184833/30723212-99052894-9eea-11e7-9c91-9f2229e7e855.png)

- [x] background 45 pixels tall
- [x] 1 pixel rule, hex #55184D
- [x] fill is hex#FFFFFF
- [x] text is hex #55184D
- [x] text is source sans regular caps, 12 pixels

_hover state_
- [x] 1 pixel rule, hex #55184D
- [x] fill is hex#55184D
- [x] text is hex #FFFFFF

Footer newsletter sign up
- [x] background hover state is hex#55184D
