### ISSUE TITLE
Bene Theme Improvements

### ISSUE THREAD

**Issue by heypaxton** [thinkshout/bene#164]
## Overview
List of items to make theming Bene sites easier. 

## This ticket is done when:
- [ ] Abstract color values into sass map
- [ ] Abstract link and button styles
- [ ] Add vars for state (hover, active, border)
- [ ] Remove donate code from parent theme
- [ ] Move paragraph blocks to own files
- [ ] Remove over specific CSS selectors in parent
- [ ] Use same file names in parent/child theme
- [ ] Declare font face in base file only
- [ ] Design newsletter block styles (newsletter / external links 
- [ ] Image style for tile on small screen when bg image over text
- [ ] Abstract listing page so that font and button styles apply based overall theme
- [ ] Add wysiwyg field to hero block open text field to allow us to theme in different ways or always same order of elements
- [ ] Remove bg header on tiles
- [ ] All text styles defined in base.scss for wysiwyg
- [ ] Standardize padding and margin structure for paragraphs
- [ ] Remove donate button code (last child elements in nav)

- [ ] Identify variables needed
- [ ] get a list of entity types that display
- [ ] examine each entity type to learn what variables are needed
- [ ] define the variables
- [ ] use the variables in the (sass and css output) styles
- [ ] examine child themes to find where themes can inherit variables from bene_base
- [ ] examine child themes to find if there are non-css-variable items that should be moved into bene-base
