### ISSUE TITLE
Support: Automated Testing

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#281]
## Overview

As Bene does not contain much custom code, automated testing should cover the following:

1. User roles and permissions (as a part of testing creating/accessing each type)
1. Content types
1. Custom block types
1. Paragraph types
1. Bene media
1. PHP code style
1. SCSS code style
1. Javascript code style

For feature testing, we’ll exclusively use Behat. If we have time, specific custom code should also be tested with Functional, Kernel, or Unit Drupal tests (in that priority order).

## This ticket is done when:
- [ ] Setup Behat and CircleCI to run for Bene (including deployment)
- [ ] Test the Listing Page content type
- [ ] Test the Event content type
- [ ] Test the Page content type
- [ ] Test the News content type
- [ ] Test the Background Image Hero custom block type
- [ ] Test the Tile/Tiles paragraph type
- [ ] Test the Media paragraph type
- [ ] Test the Feature Full Width paragraph type
- [ ] Test the Rich Text paragraph type
- [ ] Add PHPCS to CircleCI and fix existing errors
- [ ] Add scss-lint to CircleCI and fix existing errors
- [ ] Add ESlint to CircleCi (ref https://www.drupal.org/node/1955232) and fix existing errors
