### ISSUE TITLE
Support: Client Site Testing

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#286]
## Overview

For client testing, visual regression testing will provide the most value for testing Bene updates. This should be Wraith-based and run locally until we can budget a paid solution.

## Dev [6 hrs]

Setup an example Wraith script on Bene project or Bene, and at least one Bene client.

## This ticket is done when:
- [ ] Setup and document Wraith in bene-project
- [ ] Use the same setup on an existing Bene customer, make sure it works and will provide value for them/us
- [ ] If possible, set up Wraith for all other Bene customers.

**Comment by mortenson** [comment]
This seems like a good solution too and is modern/maintained: https://github.com/garris/BackstopJS Let's check out both.

**Comment by unclegcb** [comment]
@olivierbouwman did you do any experimenting with BackstopJS when researching VRT tools?

**Comment by olivierbouwman** [comment]
@unclegcb @mortenson I read up on it a little, long ago. Might be a good option in some cases. We should compare it to the new screener setup I just installed on ChangeLabs. New version is quite different, all based around PRs/branches, really liking it so far over the previous workflow. Not using multidevs anymore, measuring changes over time between a main branch and each feature branch. Guessing this workflow will be hard to achieve with BackstopJS but we should research it.

**Comment by olivierbouwman** [comment]
We should go with the screener.io approach that we're using for other clients.
- [ ] Do we want to use screener since all sites will use our account? Too costly for a per-account basis. Perhaps we use screener as long as Bene site is under maintenance.
- [ ] Can we add screener code to thinkshout/bene? Does that go downstream when bene gets updated?
