### ISSUE TITLE
Update to 8.7.0 and research Layout Builder

### ISSUE THREAD

**Issue by mortenson** [thinkshout/bene#345]
## Overview

There has been a lot of interest in layout builder, which became stable in Drupal 8.7.0. We'd like to try using it as a replacement for display suite and field group, for entity view displays, and long term using it as a replacement for paragraphs for landing page use cases.

## This ticket is done when:
- [x] Update a test Bene site to Drupal 8.7.0 
- [x] Install Layout Builder
- [x] See and document what breaks right away, if anything
- [x] For each content type, open an issue to move it to using layout builder defaults (or maybe start with one)
- [x] Make sub-issues to make block types for each paragraph type used for landing pages
- [x] Make sub-issues for each landing page style content type to start using layout builder overrides

**Comment by mortenson** [comment]
Created #346 as one issue as enabling layout builder doesn't cause any critical errors in my testing. I have a feeling this is because Bene uses custom templates instead of field group/display suite.
